#!/bin/sh
apt-get update
apt-get upgrade
apt install -y gnupg
apt install -y curl
apt install -y lsb-release
sh -c 'echo "deb http://172.17.0.1/building/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/moveit-latest.list'
curl -sSL http://172.17.0.1/public.key | apt-key add -
sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list'
apt-key adv --keyserver 'hkp://keyserver.ubuntu.com:80' --recv-key C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654
apt-get update
